### PR TITLE
ID3v2_Tag_get_frame now takes const char* and moved TagHeader_free to public header.

### LINKED ISSUE #44: `TagHeader_free` is private.
`TagHeader_free` doesn't seem to be part of the public interface, but there are public functions which return `ID3v2_TagHeader*`, so it probably should be made part of the public interface or removed entirely in favour of `free` (which it wraps) to avoid misleading people.

### LINKED ISSUE #45: `ID3v2_Tag_get_frame`  should take `frame_id` as `const char*`.
This makes it easier to pass in string constants like ` static constexpr const char* kPrivateFrameType = "PRIV";`.

### PR DESCRIPTION
**Pull request by sizeak**
fixes #44 
fixes #45

### CODE REVIEW

**Comment by larsbs** [comment]
LGTM, thanks for your contribution! 👍

**Comment by sizeak** [comment]
And thank you for the library!

**Comment by sizeak** [comment]
@larsbs Would you mind publishing a new release tag that includes these changes, I need to be able to pull a tarball for a Conan recipe. Thanks!

**Comment by larsbs** [comment]
@simoncent done, you can find the changes under the release tag 2.1

**Comment by sizeak** [comment]
Excellent, thank you 👍🏻

**Comment by sizeak** [comment]
Conan package PR is here if you;re interested https://github.com/conan-io/conan-center-index/pull/17779

**Pull request merged**
